### ISSUE TITLE
Dialyzer warnings with OTP 19

### ISSUE THREAD

**Issue by aaronjensen** [elixir-lang/gettext#115] opened 2016-08-16 19:20 UTC
Brand new phoenix app created with `mix phoenix.new` on OTP 19 has these warnings.

Here's a repro app: https://github.com/aaronjensen/dialyzer_repro

Irrelevant warnings are omitted. Originally reported at https://github.com/phoenixframework/phoenix/issues/1872

```
Starting Dialyzer
dialyzer --no_check_plt --plt /Users/aaronjensen/.dialyxir_core_19_1.3.2.plt -Wunmatched_returns -Werror_handling -Wrace_conditions -Wunderspecs /Users/aaronjensen/Source/dialyzer_repro/_build/dev/lib/dialyzer_repro/ebin
  Proceeding with analysis...
gettext.ex:1: Function lngettext/6 has no local return
gettext.ex:1: The call 'Elixir.Gettext.Interpolation':interpolate(_@7::any(),_@8::#{'count':=_, _=>_}) breaks the contract (binary(),#{}) -> {'ok',binary()} | {'error',binary()}
gettext.ex:23: Function lngettext/5 has no local return
 done in 0m3.37s
done (warnings were emitted)
```

**Comment by whatyouhide** [comment] 2016-08-16 20:57
@josevalim is this a dialyzer bug as well or should I look into it? :)

**Comment by josevalim** [comment] 2016-08-16 21:33
They don't seem to be dialyzer bugs. They look like a missing spec for lngettext functions (they are required when there is no local return) and the other one looks like dialyzer thinks we are passing more than string to interpolate. Both can probably be fixed by specifying specs for lngettext.

**Comment by whatyouhide** [comment] 2016-08-16 21:39
Got it, gonna do this then :)

**Comment by whatyouhide** [comment] 2016-08-20 15:03
@aaronjensen I just pushed a couple of commits that may fix part of this, can you give it a try again and report if you get any more warnings? :)

**Comment by aaronjensen** [comment] 2016-08-20 15:33
Different ones now:

```
gettext.ex:1: The call 'Elixir.Gettext.Interpolation':interpolate(_@7::any(),_@8::#{'count':=_, _=>_}) breaks the contract (binary(),#{}) -> {'ok',binary()} | {'error',binary()}
gettext.ex:23: The specification for 'Elixir.DialyzerRepro.Gettext':lgettext/4 states that the function might also return {'ok',binary()} but the inferred return is {'default',binary()} | {'error',<<_:64,_:_*8>>}
gettext.ex:23: Function lngettext/5 has no local return
gettext.ex:23: The call 'Elixir.DialyzerRepro.Gettext':lngettext(x0@1::any(),x1@1::any(),x2@1::any(),x3@1::any(),x4@1::any(),#{}) will never return since it differs in the 6th argument from the success typing arguments: (any(),any(),any(),any(),any(),maybe_improper_list())
```

**Comment by edevil** [comment] 2016-10-12 12:11
I also have these warnings with Elixir 1.3.4, OTP 19.1, Phoenix 1.2.1, dialyxir 0.3.5, gettext 0.11.0:
```
gettext.ex:1: Function lngettext/6 has no local return
gettext.ex:1: The call 'Elixir.Gettext.Interpolation':interpolate(_@7::any(),_@8::#{'count':=_, _=>_}) breaks the contract (binary(),#{}) -> {'ok',binary()} | {'error',binary()}
gettext.ex:23: Function lngettext/5 has no local return
```

**Comment by whatyouhide** [comment] 2016-10-13 09:19
I'm gonna try looking into this later in the weekend and I'll leave myself as the assignee so that I remember to do it but it someone wants to tackle this please feel free to go ahead! 😃

**Comment by Toady00** [comment] 2016-11-08 21:29
Using the same as @edevil except dialyxir 0.4, the only gettext warning I'm getting is

```
gettext.ex:23: Expression produces a value of type 'ok' | {'error',_}, but this value is unmatched
```

**Comment by waiting-for-dev** [comment] 2017-06-30 08:48
In my case:
```
lib/eventbox/web/gettext.ex:1: The pattern #{} can never match since previous clauses completely covered the type #{'count':=_, _=>_}
```

With:

- Erlang/OTP 19 [erts-8.2.1]
- Elixir 1.4.1
- Dialyzer 3.0.3

**Comment by whatyouhide** [comment] 2017-10-06 12:56
Hey folks, how are these warnings looking with OTP 20?

**Comment by waiting-for-dev** [comment] 2017-10-06 14:01
Mine is the same with:

- Erlang/OTP 20 [erts-9.0.2]
- Elixir 1.5.1
- Gettext 0.13.1

**Comment by whatyouhide** [comment] 2018-02-19 19:22
I tried reproducing this with current stuff by:

1. Creating a new project with `mix phx.new hello_world` on Elixir 1.6.1 and Erlang 20.1
1. Changing the Gettext dependency to `{:gettext, github: "elixir-lang/gettext"}`
1. Adding `{:dialyxir, ">= 0.0.0"}` as a dependency and adding the config `dialyzer: [plt_add_deps: :transitive]`
1. Running `mix dialyzer`

but I get no dialyzer warnings with this. I will go ahead and close this issue, please open a new one if you still have problems with the latest Gettext version and the latest Erlang/Elixir versions (with steps to reproduce please 💟).

Thanks all for your input :)

**Closed by whatyouhide** 2018-02-19 19:22 UTC
Labels: Kind:Bug, Level:Intermediate

**Comment by kuroda** [comment] 2019-05-12 12:27
@whatyouhide

I confirmed that I did not get warnings in the way you described, but I realized that I would get a warning when I actually put in the translation data.

Here is how to reproduce the problem.

After creating a phoenix `hello_world` application and installing dialyxir, modify the `priv/gettext/en/LC_MESSAGES/errors.po` as follows:

```
msgid "should be %{count} character(s)"
msgid_plural "should be %{count} character(s)"
msgstr[0] "should be %{count} character(s)"
msgstr[1] "should be %{count} character(s)"
```

Then, run `mix dialyzer`. You will see the following warning:

```
lib/hello_world_web/gettext.ex:1:pattern_match_cov
The pattern
%{}

can never match since previous clauses completely cover the type
%{:count => _, _ => _}
```

My environment:

* Erlang/OTP 21
* Elixir 1.8.1
* Phoenix 1.4.3
* Dialyxir 1.0.0-rc.6

I got `:gettext` from the github repository.

**Comment by focused** [comment] 2019-09-17 14:22
I get the same warnings (18 warnings) with elixirLS extension in vscode (auto dializer) just after adding second language (RU) with multiple pluralization forms in my phoenix application:
```
The pattern 
          #{} can never match since previous clauses completely covered the type 
          #{'count' := _, _ => _}
```

Fast workaround would be:
```elixir
defmodule TechranchWeb.Gettext do
  @dialyzer :no_match
  ...
end
```

Notice that it won't happen if I have only one default translation (EN)
