### ISSUE TITLE
Setting write_reference_comments not working

### ISSUE THREAD

**Issue by pachopepe** [elixir-lang/gettext#180] opened 2018-04-27 23:50 UTC
I configure gettext on mix.exs 
```
def project do
    [
      app: :admin,
      version: "0.0.1",
      build_path: "../../_build",
      config_path: "../../config/config.exs",
      deps_path: "../../deps",
      lockfile: "../../mix.lock",
      aliases: aliases(),
      elixir: "~> 1.4",
      elixirc_paths: elixirc_paths(Mix.env()),
      compilers: [:phoenix, :gettext] ++ Mix.compilers(),
      start_permanent: Mix.env() == :prod,
      gettext: [write_reference_comments: false],
      deps: deps()
    ]
  end
```
but gettext continue generating comments

Also, I tried setting it in the `config.exs` with no success.

**Comment by josevalim** [comment] 2018-04-28 04:14
@pachopepe which gettext version are you using?

**Comment by josevalim** [comment] 2018-07-31 11:39
Closing due to lack of information, please let us know if this is still relevant.

**Closed by josevalim** 2018-07-31 11:39 UTC

**Comment by nicolasgarnil** [comment] 2018-09-26 10:54
Not working to me as well. 

Version: `0.16.0`.

**Comment by josevalim** [comment] 2018-09-26 11:15
@nicolasgarnil which gettext version are you using? What does "not working" mean? Which behaviour are you seeing and what do you expect? Please open a new issue and try to provide as much information as you can. If you have a way to reproduce the problem, even better, as that will speed up the fixing/resolution process.

**Comment by nicolasgarnil** [comment] 2018-09-26 12:09
@josevalim Done, please see https://github.com/elixir-lang/gettext/issues/190. 

I am willing to fix it if you point me on the right direction.
