### ISSUE TITLE
'No case clause matching: 2'

### ISSUE THREAD

**Issue by 0nkery** [elixir-lang/gettext#149] opened 2017-02-24 12:22 UTC
Hello. I am using Gettext in Phoenix and trying to setup translations for my project.

Here is my translation for `Ecto` errors.
```
msgid "should be at least %{count} character(s)"
msgid_plural "should be at least %{count} character(s)"
msgstr[0] "Требуется как минимум один символ"
msgstr[1] "Требуется как минимум %{count} символа(ов)"
```

However, attempt to translate this message crashes Phoenix Endpoint.

Here is (cutted) traceback (ask if full one is needed):
```
[error] #PID<0.414.0> running Enwatch.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api/v1/users
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: 2
        (enwatch) web/gettext.ex:1: Enwatch.Gettext.lngettext/6
        (gettext) lib/gettext.ex:616: Gettext.dngettext/6
        (ecto) lib/ecto/changeset.ex:2129: anonymous fn/3 in Ecto.Changeset.merge_error_keys/3
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/changeset.ex:2123: Ecto.Changeset.traverse_errors/2
        (enwatch) web/views/changeset_view.ex:17: Enwatch.ChangesetView.render/2
```

Tell if it my mistake, Phoenix bug or Gettext, please.

**Comment by josevalim** [comment] 2017-02-24 13:31
Can you provide a simple app that reproduces the error? My hunch is that
Russian expects three translation forms and one is missing. But the error
message should definitely be better.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by 0nkery** [comment] 2017-02-26 06:41
Here it is - https://github.com/0nkery/gettext-error-app.

Quick and dirty app. Look at commits to find out my steps to reproduce.

I made test to reproduce this error and removed all the others.

**Comment by whatyouhide** [comment] 2017-02-26 20:47
The problem is indeed what José pointed out, you're only defining two pluralization of the string, but Russian wants three and the last one (`2`) is missing there.

@josevalim I already have a fix with a good error message for this, but was wondering if maybe it'd be better to validate the whole PO file since at compile time we know the locale of the PO being compiled to BEAM and the plural module for the backend, so we can simply ask how many plural forms we expect and check each translation while we compile to BEAM. Thoughts? Am I missing some scenario maybe?

**Comment by josevalim** [comment] 2017-02-26 20:50
@whatyouhide we can check the PO at compile time, yeah. :+1:

**Comment by josevalim** [comment] 2017-02-26 20:51
Maybe we should warn at compile time so we get as many warnings as possible and not go through them one by one.

**Comment by whatyouhide** [comment] 2017-02-26 20:51
Let's warn at compile time and raise at runtime then 👍

**Comment by 0nkery** [comment] 2017-02-27 02:41
Thanks!

**Comment by whatyouhide** [comment] 2017-02-27 09:25
That's maybe a good point, but right now we have a policy of ignoring translations that are empty (`""`) when compiling a PO file so when you generate a PO, which will have all empty translations, we will ignore all of them, so you can fix the forms when actually translating the strings. Generating the right ones is a different problem though, so we should open a different issue for that I think :)

**Comment by 0nkery** [comment] 2017-02-27 09:43
Thanks for reply. So, it's possible in general and [here](https://github.com/elixir-lang/gettext/issues/151) it is.

**Comment by whatyouhide** [comment] 2017-02-27 11:32
Closing in favor of the PR #150.

**Closed by whatyouhide** 2017-02-27 11:32 UTC
Labels: Kind:Bug
