### ISSUE TITLE
Alternative to missing interpolation keys error message

### ISSUE THREAD

**Issue by leighshepperson** [elixir-lang/gettext#107] opened 2016-06-29 23:06 UTC
If you use interpolation to construct a string, and you provide it with missing keys, then it returns an error message telling you which keys are missing.

However, I need to use Gettext dynamically, and I would like it to do something a little different: If the key "key" is not present, then I would like it to return the string with place holder text "{key}".

For example, instead of this:

```elixir
Localisation.Gettext.lgettext("en", "hello_world", "score-message", %{})
{:error, "missing interpolation keys: score"}
```

I would like it to return something like this:

```elixir
Localisation.Gettext.lgettext("en", "hello_world", "score-message", %{})
{:ok, "You have scored {score} points."}
```

It would be great if the library could support this.

Unfortunately, it looks like this would be quite a big change, especially since the Interpolation module runs quite deeply in the code. 

Is there any worth in creating a branch to implement this?

**Comment by whatyouhide** [comment] 2016-06-30 08:50
Just to point out, but did you mean this call in the examples you showed:

```elixir
Localisation.Gettext.lgettext("en", "hello_world", "%{score}-message", %{})
```

? Assuming you meant that, `lgettext/4` is not public API but I'm assuming you're using it as an example to show the `{:error, _} | {:ok, _}` return value (instead of the raising that the public functions/macros do).

That said, I tend to be 👎 for this feature; I feel it's a *really* unexpected behaviour that could introduce potentially a lot and very subtle bugs (e.g., you misspell a binding and you don't see that until you look at the translated string).

What's your use case? Maybe that could help us find a better way to solve your problem. Off the top of my head, one thing I can think of doing is exposing some function in `Gettext.Interpolation` that returns all the bindings in a given string (IIRC we have something like that already, it would just be a matter of making it public). But let's look at the use case first, the less stuff we add, the easier it will be to maintain Gettext :)

**Comment by maufl** [comment] 2016-07-04 11:52
As I said in #109 I don't like this behaviour either. I understand why not raising an error might not be a good idea. On the other hand the translations are not always maintained by the developers and are not usually all covered by tests. 
So if a translator makes a mistake in a binding name, we will get a runtime error. :( 

As an example, we have a website with multiple locales. Now if the Norwegian translation contains an typo in the binding, we will never know and our customer might get an 500 instead of simply a warning like `<missing placeholer>`. I guess it is unlikely that they will report a 500 and more likely that they report a broken translation.

**Comment by whatyouhide** [comment] 2016-07-04 12:14
When there's a missing interpolation key we raise a `Gettext.Error` though, so one could implement the `Plug.Exception` protocol for `Gettext.Error` and make it raise something more reasonable or act on it accordingly. Broken translations are *really* hard to spot by developers and not users, because usually developers don't look at all the translations. Another point about translator making typos in the `msgid`s, I think they're not supposed to touch the `msgid` because that's what you want extracted by `mix gettext.extract` most of the time? (excluding dynamic translations)

Wdyt? \cc @josevalim

**Comment by josevalim** [comment] 2016-07-04 12:20
@whatyouhide well, you will still have interpolation in the msgstr and you can make a typo there. I think a good compromise would be to make this a configuration option in the backend? For production, you want to keep values you can't interpolate although for development it likely makes sense to error on missing keys?

**Comment by maufl** [comment] 2016-07-04 12:25
@whatyouhide can we even check for typos in `msgid`s if the bindings are not known at compile time?

@josevalim that sounds like a good idea. Maybe we could also provide a callback on missing translations, so that a message can be written to a log or a mail be sent to the developers?

**Comment by whatyouhide** [comment] 2016-07-04 12:29
@maufl most of the time (or at least for non-dynamic translations) we have only the string to translate at compile time, thus only the `%{bindings}` in it (but not the map of bindings passed to it).

Making this configurable is definitely an option; I'm not sure I would go with a callback like @maufl suggested because then it's gonna be hard to change this per-environment (but it would be easy to implement this for us because we could do it via an overridable function defined by `use Gettext`). With @josevalim's solution you can either raise for missing interpolations or maybe warn and leave them as `%{is}`? Was that what you had in mind José?

**Comment by josevalim** [comment] 2016-07-04 12:41
@whatyouhide yes.

**Comment by whatyouhide** [comment] 2016-07-18 17:47
So, let's revive this a bit :) Shall we go with a configurable (per-backend I think?) callback module? Or a configurable *switch* between warning and leaving as `%{is}` vs not doing anything? Wdyt?

**Comment by josevalim** [comment] 2016-07-18 18:10
@whatyouhide let's go with a callback in the backend and changing the default to keep it as `%{is}`. Then we can discuss an option later on?

**Comment by whatyouhide** [comment] 2016-07-18 18:22
Yes, let's start with a (overridable) callback that we define in `use Gettext` and document in the `Gettext.Backend` behaviour, à la `c:GenServer.init/1`.

**Comment by maufl** [comment] 2016-07-19 09:15
Or maybe we could just have a callback and the return value is substituted for the missing key?

**Comment by whatyouhide** [comment] 2016-07-19 09:17
@maufl yes, I think that's what @josevalim meant. We will have something like:

```elixir
def handle_missing_binding(binding, original_string) do
  # return value is used as the value for binding
end
```

With a default implementation that goes something like:

```elixir
def handle_missing_binding(binding, original_string) do
  IO.warn "missing binding #{inspect(binding)} in #{inspect(original_string)}"
  "%{" <> Atom.to_string(binding) <> "}"
end
```

**Comment by josevalim** [comment] 2016-07-19 17:10
Let's use Logger.warn though. :)

**Comment by josevalim** [comment] 2016-07-19 17:11
Let's also pass the locale to the function so we know which locale failed when we warn. :D

**Comment by whatyouhide** [comment] 2016-07-19 19:14
Yeah, that was a sucky implementation just to show how it would work, I randomly chose `binding` and `original_string` 😄 No `IO.warn` because we need to support Elixir >= 1.1 and yes, let's pass the locale.

**Comment by maufl** [comment] 2016-07-21 12:09
So I looked into it, but I'm not quite sure how to implement it. `Gettext.Interpolation.interpolate` does not hold a reference to the current backend and passing it just for the missing handler feels not right :confused: 
How would you call the `handle_missing_binding` method from `interpolate`?
And where does the default implementation go, into the `__using__()` macro of `Gettext`? That feels unclean.

What about specifying the handler in a `mix` config file like [canary](https://github.com/cpjk/canary#handling-unauthorized-actions)? This would also allow for different handlers based on the env.

**Comment by whatyouhide** [comment] 2016-07-21 12:24
> And where does the default implementation go, into the` __using__()` macro of `Gettext`? That feels unclean.

Why so? It's what something like [`GenServer`](https://github.com/elixir-lang/elixir/blob/c6a25729e08ee6eee3bbfcc44d6bf99d00a17653/lib/elixir/lib/gen_server.ex#L502-L549) does as well for example.

I think we should call the `handle_missing_binding` handler from inside the backend, not from `interpolate`. I haven't looked very well but off the top of my head we could just change the return value of `interpolate` to something like `{:error, {:missing_bindings, required, present}}` and then call `handle_missing_bindings` with them, and in the default implementation call `Interpolation.missing_interpolation_keys` to generate the message. Makes sense?

**Comment by josevalim** [comment] 2016-07-21 12:28
> I think we should call the handle_missing_binding handler from inside the backend, not from interpolate

The interpolation code should compile to something like this:

    interpolate(locale, map, key, original)

where:

    defp interpolate(locale, map, key, original) do
      case map do
        %{^key => value} -> value
        %{} -> handle_missing_interpolation(locale, key, original)
        _ -> raise "not a map yo"
      end
    end

and it should just assume handle_missing_interpolation will be available in the context it is used on. That's for the compiled code. For the non-compiled code it is slightly trickier but should be doable similarly.

**Comment by whatyouhide** [comment] 2016-07-21 12:30
Yeah you're right @josevalim, that's how it is supposed to look in the compiled code. I guess my reasoning applies well to the non-compiled code though? :)

**Comment by whatyouhide** [comment] 2016-07-25 10:16
@maufl did you get what me and @josevalim discussed about above? Let me know if anything was unclear of if you need any kind of help :)

**Comment by maufl** [comment] 2016-07-26 08:11
Sorry, I was busy working on my university courses over the weekend :/
Actually, I did not fully get what @josevalim means, but I think it's because I do not completely understand the interpolation code right now. Isn't the `msgstr` interpolated in one go right now? The signature of the `interpolate` method from @josevalim looks totally different from the current one. Do you want to make a macro out of it, that is expanded in the backend?

**Comment by whatyouhide** [comment] 2016-07-26 08:23
@maufl interpolation is done differently depending on the msgid being passed at compile time (to one of the Gettext macros in a Gettext backend) or at runtime (to, the `Gettext.*gettext` functions). In the first case, we compile something like:

```elixir
gettext "Hello %{name1} and %{name2}", %{name1: "foo", name2: "bar"}
```

to something like:

```elixir
case bindings do
  %{name1: name1, name2: name2} ->
    {:ok, "Ciao " <> name1 <> " and " <> name2}
  _ ->
    {:error, ...}
end
```

We can do this to optimize speed because we have both the msgid and msgstr at compile time. Does this help clarify things a bit? :) Please feel free to keep asking questions, this is not the most straightforward code around. Also feel free to hit me up on the #elixir-lang IRC if you want to chat :)

**Comment by maufl** [comment] 2016-07-27 09:27
Ok, I think I understood now how the compilation of PO files works and where the interpolation happens. Also, as this will be important to our project, I can work on this today at work :)
I'm just still not sure how to do it for dynamic translations. I'll be back with a PR and then we can discuss it further.

**Comment by whatyouhide** [comment] 2016-07-27 09:28
Awesome @maufl, sounds like a great plan :)

**Comment by maufl** [comment] 2016-07-27 12:04
Ok, so I'm struggeling to implement this. I opened a pull request so that we can discuss it with code #113

**Comment by josevalim** [comment] 2016-10-22 15:01
Closing in favor of #129.

**Closed by josevalim** 2016-10-22 15:01 UTC
Labels: Kind:Discussion, Kind:Feature
